# adapted from https://github.com/mila-iqia/ResearchTemplate/

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-added-large-files
        args: ["--maxkb=1000"] # 1MB
        require_serial: true
      - id: check-ast
        require_serial: true
      - id: check-case-conflict
        require_serial: true
      - id: check-yaml
        require_serial: true
      - id: debug-statements
        require_serial: true
      - id: detect-private-key
        require_serial: true
      - id: end-of-file-fixer
        require_serial: true
      - id: trailing-whitespace
        require_serial: true

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.12.11"
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: ["--line-length", "88", "--fix"]
        require_serial: true
      - id: ruff-format
        types_or: [ python, pyi ]
        require_serial: true

  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    # Don't autoupdate until https://github.com/PyCQA/docformatter/issues/293 is fixed
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        language: python
        additional_dependencies: [tomli]
        args: [--in-place, --wrap-summaries=88, --wrap-descriptions=88]
        require_serial: true

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        require_serial: true

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args:
          - --skip=assets/**, data/**, experiments/results/**,
        require_serial: true
